mybloger1/config/routes.rb
Rails.application.routes.draw do
  get 'controls/login'

#get 'users/login'

 root "articles#index"
  resources :articles  do
 resources :comments
  	end
  resources :users
  match ':controller(/:action(/:id))',:via=> [:get ,:post]
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

mybloger1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

mybloger1/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

mybloger1/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

mybloger1/app/models/user.rb
class User < ApplicationRecord
	has_many  :articles
end

mybloger1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

mybloger1/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    if  session[:user].nil? 
   redirect_to "/controls/login"
    else
    @article = Article.new
    @article.user_id= session[:user].to_i 
  end
  
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
     @article.user_id= session[:user].to_i 
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :user_id)
    end
end

mybloger1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

@article=Article.find(params[:article_id])
@comment=@article.comments.new(comment_params)
#@comment.user_id=session[:user].to_i
@comment.save
redirect_to article_path(@article)

	end

	private
	def comment_params
      params.require(:comment).permit(:body)
	end

 
end

mybloger1/app/controllers/controls_controller.rb
class ControlsController < ApplicationController
  def login
  	 if request.post?
    user = User.find_by(:email=>params[:email], :password=>params[:password]) 
      if !user.nil?
         session[:user] = user.id
        redirect_to root_url, notice: "Thank you for signing up  "
      
      else
        respond_to do |format|
         format.html { render :new }
         format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end


     #else
      # @user = User.new 
    end
  end

  def logout

session[:user]=nil
 redirect_to root_url, notice: "Thank you for signing up  "
      
  end
end

mybloger1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

 
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

mybloger1/app/helpers/application_helper.rb
module ApplicationHelper
end

mybloger1/app/helpers/articles_helper.rb
module ArticlesHelper
end

mybloger1/app/helpers/comments_helper.rb
module CommentsHelper
end

mybloger1/app/helpers/controls_helper.rb
module ControlsHelper
end

mybloger1/app/helpers/users_helper.rb
module UsersHelper
end

mybloger1/app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title ,   :class => "form-control" %>
  </div>

  <div class="field" >
    <%= f.label :body %>
    <%= f.text_area :body , :size => "20x20", :class => "form-control" %>
  </div>
 
  <div class="actions">
    <%= f.submit  class:"btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

mybloger1/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article  %> |
<%= link_to 'Back', articles_path %>

mybloger1/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
 
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
 
        <td><%= article.user.email %></td>
        <td><%=  link_to 'Show', article,:class=>"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_article_path(article) ,:class=>"btn btn-info"   if  !session[:user].nil? %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-info"   if  !session[:user].nil? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path,:class=>"btn btn-success"%>

mybloger1/app/views/articles/new.html.erb
 
<div class="panel panel-default">
  <div class="panel-heading"> New Article</div>
  <div class="panel-body"> 

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path  %>

    </div>
</div>

mybloger1/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
 
<div class="panel panel-default">
  <div class="panel-heading"><p>
  <strong>Title:</strong>
  <%= @article.title %>
</p></div>
  <div class="panel-body"> 

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.email %>
</p>

      <div class="panel panel-default">
  <div class="panel-body"> 
<table class="table">
  <thead>
    <tr>
      <th> visitor comments</th>
    </tr>
  </thead>
 <tbody>
    <% @article.comments.each do |comment| %>
      <tr>
        <td>
    
          <%= comment.body %>
     
        </td>
           <td><%# comment.user.email %></td>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>
     </div>
</div>
</div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">add comment</div>
  <div class="panel-body"> 

<%= form_for([@article,@article.comments.build]) do |f| %>
 

  <div class="field">
 
    <%= f.text_area :body ,:class => 'form-control' %>
  </div>


  <div class="actions">
    <%= f.submit  class:"btn btn-success" %>
  </div>
<% end %>
</div>
</div>
 



<%= link_to 'Edit', edit_article_path(@article) ,:class=>"btn btn-info"%> |
<%= link_to 'Back', articles_path ,:class=>"btn btn-info" %>
   </div>
</div>

mybloger1/app/views/controls/login.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Please sign in</div>
  <div class="panel-body"> 

   
<%= form_tag( :url => { :action => "login" }, method: "post" ) do  %>
  

  <div class="field">
    <%= label_tag :email  %>
    <%= text_field_tag :email , '', :class => "form-control"    %>
  </div>

  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password , '', :class => "form-control"  %>
  </div>

  <div class="actions">
    <%= submit_tag "Sign in" ,class:"btn btn-lg btn-primary btn-block"%>
  </div>
<% end %>
<%= link_to 'New User', "/users/new" , :class=>"btn btn-success" %>
 </div>
</div>

mybloger1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Bloger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">The Bloger</a>
    </div>
    <ul class="nav navbar-nav">
       <li> 
      	<%= link_to 'Article', "/articles" %> </li>
      <li> 
      	<%= link_to 'Login', "/controls/login"  if  session[:user].nil? %> </li>
      <li> 
      	<%= link_to 'Profile', "/users/#{session[:user] }"   if  !session[:user].nil? %> </li>
      	 <li> 
      		<%= link_to 'Manage', "/users"   if  !session[:user].nil? %> </li>
 <li> 
      		<%= link_to 'Log out', "/controls/logout"   if   !session[:user].nil? %> </li>

    </ul>
  </div>
</nav>
  
<div class="container">
    <%= yield %>
</div>

  </body>
</html>

mybloger1/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email ,   :class => "form-control"%>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password ,   :class => "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

mybloger1/app/views/users/edit.html.erb
 
<div class="panel panel-default">
  <div class="panel-heading">Editing User</div>
  <div class="panel-body"> 
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</div>
</div>

mybloger1/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user ,:class=>"btn btn-info"%></td>
        <td><%= link_to 'Edit', edit_user_path(user) ,:class=>"btn btn-info"%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' ,:class=>"btn btn-info"} ,:class=>"btn btn-info"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path , :class=>"btn btn-success" %>

mybloger1/app/views/users/new.html.erb
 
<div class="panel panel-default">
  <div class="panel-heading">New User</div>
  <div class="panel-body"> 
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

</div>
</div>

mybloger1/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
 
<div class="panel panel-default">
  <div class="panel-heading">Profile</div>
  <div class="panel-body"> 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

</div>
</div>